### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#2]
https://github.com/bakakoozin/Zozor/blob/11c18dafea3ad9340701b3d915842a0b5117c8b7/section.css#L18-L19

La position gérée avec des margin ? 

De plus, la position n'est pas bien fixée, elle devrait être liée au séparateur

**Comment by bakakoozin** [comment]
la modif est faite, l'icône est liée au séparateur

**Comment by kazerlelutin** [comment]
La position est toujours géré par des marges

**Comment by kazerlelutin** [comment]
```css
main {
    background-color: #f8eccc;
    padding: 0px 50px 0px 50px;
    display: flex;
    flex-direction: column;
    gap: 2rem;
}
```

**Comment by bakakoozin** [comment]
modifié

**Comment by kazerlelutin** [comment]
```css
main {
    background-color: #f8eccc;
    padding: 0px 50px;
    display: flex;
    flex-direction: column;
    gap: 2rem;
}
```
