### ISSUE TITLE
Titres

### ISSUE THREAD

**Issue by kazerlelutin** [bakakoozin/Zozor#4]
https://github.com/bakakoozin/Zozor/blob/11c18dafea3ad9340701b3d915842a0b5117c8b7/index.html#L35C14-L38C33

Autant de H1 ? pas adapté, changer de balise. 

```css
.menu h1 {
    margin-left: 20px;
    padding-bottom: 3px;
}
```

Non, il y a moyen de faire mieux.
